#!/bin/bash

set -e -x

if [ "${DOC}" != "0" ]; then
    bin/travis-sphinx build
    exit 0
fi

if [ "${ROBOT}" != "0" ]; then
    cp robot/config_80.py_template robot/config_80.py
    sed -i 's#ODOO_DB = "demo"#ODOO_DB = "openerp_test"#g' robot/config_80.py
    exit 0
fi

bin/test_openerp -d openerp_test -i open_academy

set +e +x
